// nuxt-svai/pages/order.vue
<template>
  <div class="container mx-auto px-4 py-12 max-w-3xl">
    <h1 class="font-display text-3xl mb-6">Оформить заявку</h1>

    <div v-if="!cart.length" class="text-[oklch(0.45_0.02_50)]">
      Корзина пуста. <NuxtLink to="/catalog" class="text-brand underline">Перейти в каталог</NuxtLink>
    </div>

    <template v-else>
      <!-- Cart table -->
      <table class="w-full mb-6 border border-[oklch(0.85_0.02_70)] text-sm">
        <thead class="bg-[oklch(0.93_0.015_75)]">
          <tr>
            <th class="text-left p-3">Товар</th>
            <th class="text-center p-3">Кол-во</th>
            <th class="text-right p-3">Цена</th>
            <th class="text-right p-3">Сумма</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="item in cart" :key="item.product_id" class="border-t border-[oklch(0.85_0.02_70)]">
            <td class="p-3">{{ item.name }}</td>
            <td class="p-3 text-center">{{ item.qty }}</td>
            <td class="p-3 text-right">{{ formatRub(item.price + item.install_price) }}</td>
            <td class="p-3 text-right">{{ formatRub((item.price + item.install_price) * item.qty) }}</td>
          </tr>
          <tr class="border-t border-[oklch(0.85_0.02_70)] font-bold">
            <td colspan="3" class="p-3 text-right">Итого:</td>
            <td class="p-3 text-right text-brand">{{ formatRub(grandTotal) }}</td>
          </tr>
        </tbody>
      </table>

      <form @submit.prevent="handleSubmit" class="space-y-4">
        <div>
          <label class="block text-sm font-medium mb-1">Имя *</label>
          <input
            v-model="customer.name"
            required
            class="w-full rounded-md border border-[oklch(0.85_0.02_70)] px-3 py-2 text-sm focus:outline-none focus:border-[oklch(0.42_0.16_25)]"
          />
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">Телефон *</label>
          <input
            v-model="customer.phone"
            required
            class="w-full rounded-md border border-[oklch(0.85_0.02_70)] px-3 py-2 text-sm focus:outline-none focus:border-[oklch(0.42_0.16_25)]"
          />
        </div>
        <div>
          <label class="block text-sm font-medium mb-1">E-mail *</label>
          <input
            v-model="customer.email"
            type="email"
            required
            class="w-full rounded-md border border-[oklch(0.85_0.02_70)] px-3 py-2 text-sm focus:outline-none focus:border-[oklch(0.42_0.16_25)]"
          />
        </div>
        <button
          type="submit"
          :disabled="submitting"
          class="w-full h-12 flex items-center justify-center text-sm font-semibold rounded-md bg-[oklch(0.42_0.16_25)] hover:bg-[oklch(0.42_0.16_25)]/90 text-[oklch(0.98_0.01_80)] disabled:opacity-50 transition"
        >
          {{ submitting ? 'Отправка...' : 'Отправить заявку' }}
        </button>
      </form>
    </template>
  </div>
</template>

<script setup lang="ts">
import { formatRub } from '~/utils/format'
import { useCart } from '~/composables/useCart'
import { useToast } from '~/composables/useToast'

useHead({ title: 'Оформить заявку — Завод винтовых свай' })

const { cart, grandTotal, clear } = useCart()
const { success, error } = useToast()
const router = useRouter()

const submitting = ref(false)
const customer = reactive({ name: '', phone: '', email: '' })

const handleSubmit = async () => {
  submitting.value = true
  try {
    const res = await $fetch('/api/orders', {
      method: 'POST',
      body: {
        contact_name: customer.name.trim(),
        contact_phone: customer.phone.trim(),
        contact_email: customer.email.trim(),
        items: cart.value.map((i) => ({
          product_id: i.product_id,
          name: i.name,
          price: i.price + i.install_price,
          qty: i.qty,
        })),
      },
    }) as any

    success('Заявка отправлена!')
    clear()
    router.push('/')
  } catch (err: any) {
    error(err?.data?.message || 'Ошибка сети')
  } finally {
    submitting.value = false
  }
}
</script>

// src/routes/order.tsx
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { formatRub } from "@/lib/format";
import { useServerFn } from "@tanstack/react-start";
import { sendOrderEmail } from "@/lib/email.functions";

export const Route = createFileRoute("/order")({
  component: OrderPage,
});

function OrderPage() {
  const navigate = useNavigate();
  const [cart, setCart] = useState<Array<{ product_id: string; name: string; price: number; install_price: number; qty: number }>>([]);
  const [loading, setLoading] = useState(true);
  const [customer, setCustomer] = useState({ name: "", phone: "", email: "" });
  const [submitting, setSubmitting] = useState(false);
  const sendEmail = useServerFn(sendOrderEmail);

  // Load cart once on mount
  useEffect(() => {
    const saved = localStorage.getItem("cart");
    if (saved) setCart(JSON.parse(saved));
    setLoading(false);
  }, []);

  const total = cart.reduce((s, i) => s + (i.price + i.install_price) * i.qty, 0);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!customer.name || !customer.phone || !customer.email) {
      toast.error("Заполните все поля");
      return;
    }
    setSubmitting(true);
    try {
      const res = await sendEmail({
        data: {
          cart: cart.map((i) => ({
            product_id: i.product_id,
            name: i.name,
            price: i.price + i.install_price,
            qty: i.qty,
          })),
          customer: {
            name: customer.name.trim(),
            phone: customer.phone.trim(),
            email: customer.email.trim(),
          },
        },
      });
      if (res.success) {
        toast.success("Заявка отправлена!");
        localStorage.removeItem("cart");
        setCart([]);
        navigate({ to: "/" });
      } else {
        toast.error("Ошибка отправки заявки");
      }
    } catch (err: any) {
      toast.error(err?.message || "Ошибка сети");
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) return <div className="container mx-auto px-4 py-12 text-center">Загрузка…</div>;

  return (
    <div className="container mx-auto px-4 py-12 max-w-3xl">
      <h1 className="font-display text-3xl mb-6">Оформить заявку</h1>
      {cart.length === 0 ? (
        <p className="text-muted-foreground">Корзина пуста.</p>
      ) : (
        <>
          <table className="w-full mb-6 border border-border">
            <thead className="bg-muted">
              <tr>
                <th className="text-left p-2">Товар</th>
                <th className="text-center p-2">Кол‑во</th>
                <th className="text-right p-2">Цена</th>
                <th className="text-right p-2">Сумма</th>
              </tr>
            </thead>
            <tbody>
              {cart.map((i) => (
                <tr key={i.product_id} className="border-t border-border">
                  <td className="p-2">{i.name}</td>
                  <td className="p-2 text-center">{i.qty}</td>
                  <td className="p-2 text-right">{formatRub(i.price + i.install_price)}</td>
                  <td className="p-2 text-right">{formatRub((i.price + i.install_price) * i.qty)}</td>
                </tr>
              ))}
              <tr className="border-t border-border font-bold">
                <td colSpan={3} className="p-2 text-right">Итого:</td>
                <td className="p-2 text-right">{formatRub(total)}</td>
              </tr>
            </tbody>
          </table>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-1">Имя</label>
              <Input
                required
                value={customer.name}
                onChange={(e) => setCustomer({ ...customer, name: e.target.value })}
              />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Телефон</label>
              <Input
                required
                value={customer.phone}
                onChange={(e) => setCustomer({ ...customer, phone: e.target.value })}
              />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">E‑mail</label>
              <Input
                type="email"
                required
                value={customer.email}
                onChange={(e) => setCustomer({ ...customer, email: e.target.value })}
              />
            </div>
            <Button
              type="submit"
              disabled={submitting}
              className="w-full bg-brand hover:bg-brand/90 text-brand-foreground h-12"
            >
              {submitting ? "Отправка…" : "Отправить заявку"}
            </Button>
          </form>
        </>
      )}
    </div>
  );
}
